# Generated by Django 4.0.5 on 2022-06-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('PB', 'public'), ('MD', 'moderated'), ('NP', 'not published')], default='MD', max_length=2),
        ),
    ]
